CREATE DEFINER=`root`@`localhost` PROCEDURE `Limite_Creditos`()
BEGIN
	DECLARE LIMITE_CLIENTE FLOAT;
    DECLARE LIMITE_TOTAL FLOAT DEFAULT 0;
    DECLARE FIM_CURSOR INTEGER DEFAULT 0;
	DECLARE c CURSOR FOR SELECT LIMITE_DE_CREDITO FROM tabela_de_clientes;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM_CURSOR = 1;
    OPEN c;
    WHILE FIM_CURSOR = 0
    DO
		FETCH c INTO LIMITE_CLIENTE;
        IF FIM_CURSOR = 0 THEN
			SET LIMITE_TOTAL = LIMITE_TOTAL + LIMITE_CLIENTE;
        END IF;
    END WHILE;
    CLOSE c;
    SELECT LIMITE_TOTAL;
END