call p_inserir_venda('2019-05-17', 3, 100);




SELECT A.NUMERO, COUNT(*) AS NUMERO_ITENS, SUM(B.QUANTIDADE * B.PRECO) AS FATURADO
FROM NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO WHERE A.DATA_VENDA = '20190517'
GROUP BY A.NUMERO;