CREATE DEFINER=`root`@`localhost` PROCEDURE `Quantidade_Notas`()
BEGIN
	DECLARE NUMNOTAS INTEGER;
    SELECT COUNT(*) INTO NUMNOTAS FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01';
    SELECT NUMNOTAS;
END